# Creates a docker container where the root directory of LoAT is mounted to
# /LoAT and start QtCreator.

version: "3"

services:
  qtcreator:
    image: qtcreator:latest
    container_name: qtcreator
    security_opt: [seccomp:unconfined]
    cap_add: [SYS_PTRACE]
    build:
      context: .
      dockerfile: qtcreator.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/LoAT
    network_mode: host
